/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lisztian' at '9/19/17 3:00 PM' with Gradle 3.0
 *
 * @author lisztian, @date 9/19/17 3:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
