import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lisztian' at '9/19/17 3:00 PM' with Gradle 3.0
 *
 * @author lisztian, @date 9/19/17 3:00 PM
 */
public class LibraryTest {
    
}
